--예약 테이블
CREATE TABLE RESERVATION 
(
  R_NUM VARCHAR2(20)
, R_NAME VARCHAR2(40) 
, R_DEPARTURE VARCHAR2(12) 
, R_DEPARTURETIME DATE 
, R_ARRIVAL VARCHAR2(12) 
, R_ARRIVALTIME DATE 
, R_SEAT VARCHAR2(5) 
, R_ANUM VARCHAR2(20) 
, R_DATE DATE 
, R_FNAME VARCHAR2(20) 
, R_CLASS VARCHAR2(12) 
);
insert into reservation values('12345','이민정','인천','20170928')
--티켓 테이블
CREATE TABLE TICKET 
(
T_NAME VARCHAR2(40) 
, T_DATE DATE 
, T_SEAT VARCHAR2(5) 
, T_DEPARTURE VARCHAR2(12) 
, T_DEPARTURETIME VARCHAR2(12) 
, T_ARRIVAL VARCHAR2(12) 
, T_ARRIVALTIME VARCHAR2(12) 
, T_CLASS VARCHAR2(12)
, T_GATE VARCHAR2(6) 
, T_FNAME VARCHAR2(8) 
, T_BAGNUM NUMBER 
);